@token = xxxxxxxxxxxx
@ngoId = xxxxxxxxxxxx
@url = localhost:5000

POST http://{{url}}/sign-up
content-type: application/json

{
	"email": "user1@sama.network",
	"username": "user1",
	"password": "secret",
	"role": "ngo"
}

###
POST http://{{url}}/sign-in
content-type: application/json

{
	"email": "user1@sama.network",
	"password": "secret"
}

###
GET http://{{url}}/ngos

###
GET http://{{url}}/ngos/{{ngoId}}

###
GET http://{{url}}/me
content-type: application/json
authorization: bearer {{token}}

###
POST http://{{url}}/me/funds
authorization: bearer {{token}}
content-type: application/json

{
	"funds": 5000
}

###
POST http://{{url}}/ngos/{{ngoId}}/donate
authorization: bearer {{token}}
content-type: application/json

{
	"funds": 5000
}