@token = xxxxxxxxxxxxxxx
@url = localhost:5000

POST http://{{url}}/sign-up
content-type: application/json

{
	"email": "user@sama.network",
	"password": "secret",
	"role": "user"
}

Response 200 OK
{}

---------------

###
POST http://{{url}}/sign-in
content-type: application/json

{
	"email": "user@sama.network",
	"password": "secret"
}

Response 200 OK
{
  "accessToken": "secret_token",
  "refreshToken": null,
  "expires": 1526678460901
}

---------------