@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDI4N2NhMy1jNWU5LTQ3ZWUtODVjOC0zMWIxYjgxOTQ1ZDIiLCJ1bmlxdWVfbmFtZSI6IjlkMjg3Y2EzLWM1ZTktNDdlZS04NWM4LTMxYjFiODE5NDVkMiIsImp0aSI6IjJhNzRlNjFlLWQzMjEtNDFlYy04MzgwLTY4NTAxYTBkOGVmOSIsImlhdCI6IjE1MjczMTkxMTYzOTMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTUyNzMxOTExNiwiZXhwIjoxNTI3MzIyNzE2LCJpc3MiOiJzYW1hLWlkZW50aXR5LXNlcnZpY2UifQ.CpRoMFzHaAFRNauvYjM0udeVvuZtJ8eRQzdxyIH68r8
@ngoId = c44c7a31-2c24-467c-86db-aeb9dd56ad33
@childId = 
@url = localhost:5000

POST http://{{url}}/sign-up
content-type: application/json

{
	"email": "admin@sama.network",
	"username": "user1",
	"password": "secret",
	"role": "user"
}

###
POST http://{{url}}/sign-in
content-type: application/json

{
	"email": "admin@sama.network",
	"password": "secret"
}

###
GET http://{{url}}/ngos

###
GET http://{{url}}/ngos/{{ngoId}}

###
GET http://{{url}}/me
content-type: application/json
authorization: bearer {{token}}

###
POST http://{{url}}/me/funds
authorization: bearer {{token}}
content-type: application/json

{
	"funds": 5000
}

###
POST http://{{url}}/ngos/{{ngoId}}/donate
authorization: bearer {{token}}
content-type: application/json

{
	"funds": 4850
}

###
POST http://{{url}}/ngos
authorization: bearer {{token}}
content-type: application/json

{
	"name": "Some NGO",
	"description": "Some NGO description",
	"fundsPerChild": 2500,
	"location": {
		"address": "Valid address or coordinates",
		"latitude": 50.049683,
		"longitude": 19.944544
	}
}

###
POST http://{{url}}/ngos/{{ngoId}}/children
authorization: bearer {{token}}
content-type: application/json

{
	"children": [{
		"fullName": "John Doe",
		"gender": "male",
		"birthDate": "2011-05-17",
		"notes": "some notes",
		"neededFunds": 1800
	}]
}

PUT http://{{url}}/ngos/{{ngoId}}/children
authorization: bearer {{token}}
content-type: application/json

{
	"children": [{
		"id": "9146dbb7-9fe4-4af0-88d9-748fa9c60a04",
		"fullName": "John Doe",
		"gender": "male",
		"birthDate": "2011-05-17",
		"notes": "some notes",
		"neededFunds": 1800
	}]
}

###
POST http://{{url}}/ngos/{{ngoId}}/children/{{childId}/donate
authorization: bearer {{token}}
content-type: application/json

{
	"funds": 1500
}

###
POST http://{{url}}/ngos/{{ngoId}}/approve
authorization: bearer {{token}}
content-type: application/json

{
	"notes": "some notes"
}

###
POST http://{{url}}/ngos/{{ngoId}}/reject
authorization: bearer {{token}}
content-type: application/json

{
	"notes": "some notes"
}

